#!/usr/bin/env python3
"""Convert SmartIR climate codes (Broadlink, Base64) to Flipper Zero .ir files.

Default source is SmartIR codes/climate/1345.json (Tadiran, remote TAC 297),
pinned to the commit that added it so the output is reproducible.

    ./smartir_to_flipper.py                      # fetch pinned source, write ACs/Tadiran/
    ./smartir_to_flipper.py --source 1345.json   # use a local copy
"""

import argparse
import base64
import json
import re
import sys
import urllib.request
from pathlib import Path

SMARTIR_COMMIT = "5ec5215398c97abb3a1763880690f1e6718b7506"
SOURCE_PATH = "codes/climate/1345.json"
DEFAULT_SOURCE = (
    f"https://raw.githubusercontent.com/smartHomeHub/SmartIR/{SMARTIR_COMMIT}/{SOURCE_PATH}"
)
SOURCE_PAGE = f"https://github.com/smartHomeHub/SmartIR/blob/{SMARTIR_COMMIT}/{SOURCE_PATH}"

# Broadlink timing unit: 269/8192 ms (~32.84 us).
BROADLINK_UNIT_US = 269 / 8192 * 1000
FREQUENCY = 38000
DUTY_CYCLE = "0.330000"

MODE_NAMES = {
    "cool": "Cool",
    "heat": "Heat",
    "dry": "Dry",
    "fan_only": "Fan",
    "heat_cool": "Auto",
}
FAN_NAMES = {"low": "Low", "mid": "Mid", "high": "High", "auto": "Auto"}

# Flipper firmware rejects raw signals longer than this.
FLIPPER_MAX_TIMINGS = 1024
# IR Blaster refuses GitHub imports over 512 KB; keep a margin.
MAX_FILE_BYTES = 450 * 1024
# Expected start of Off (mark, space, mark, space), in us.
OFF_PREFIX = (8500, 4560, 1675, 558)


def decode_broadlink(b64):
    """Decode a Base64 Broadlink IR packet to a list of durations in microseconds."""
    packet = base64.b64decode(b64)
    if packet[0] != 0x26:
        raise ValueError(f"not a Broadlink IR packet (type byte 0x{packet[0]:02x})")
    length = packet[2] | packet[3] << 8
    payload = packet[4 : 4 + length]
    if len(payload) != length:
        raise ValueError(f"truncated packet: header says {length} bytes, got {len(payload)}")

    units = []
    i = 0
    while i < len(payload):
        if payload[i] == 0:
            # Escape: next two bytes are a big-endian duration.
            units.append(payload[i + 1] << 8 | payload[i + 2])
            i += 3
        else:
            units.append(payload[i])
            i += 1
    while units and units[-1] == 0:
        units.pop()

    timings = [round(u * BROADLINK_UNIT_US) for u in units]
    if len(timings) % 2:
        # End on a space so back-to-back sends keep their gap.
        timings.append(timings[-1] if timings[-1] > 10000 else 100000)
    return timings


def signal_name(mode, fan, temp):
    return f"{MODE_NAMES[mode]}_{FAN_NAMES[fan]}_{int(float(temp))}"


def collect_signals(commands):
    """Return [(name, timings)] with Off first, then mode -> fan -> temp in source order."""
    signals = [("Off", decode_broadlink(commands["off"]))]
    for mode, fans in commands.items():
        if mode == "off":
            continue
        for fan, temps in fans.items():
            for temp, code in temps.items():
                signals.append((signal_name(mode, fan, temp), decode_broadlink(code)))
    return signals


def render(signals, title):
    lines = [
        "Filetype: IR signals file",
        "Version: 1",
        "# ",
        f"# Tadiran AC, remote TAC 297 - {title}",
        f"# Source: SmartIR {SOURCE_PATH} (MIT), commit {SMARTIR_COMMIT[:12]}",
        "# Generated by smartir_to_flipper.py",
    ]
    for name, timings in signals:
        lines += [
            "# ",
            f"name: {name}",
            "type: raw",
            f"frequency: {FREQUENCY}",
            f"duty_cycle: {DUTY_CYCLE}",
            "data: " + " ".join(map(str, timings)),
        ]
    return "\n".join(lines) + "\n"


def build_files(signals):
    by_name = dict(signals)
    off = [("Off", by_name["Off"])]

    def pick(names):
        return off + [(n, by_name[n]) for n in names]

    def mode(prefix):
        return off + [s for s in signals if s[0].startswith(prefix + "_")]

    compact = pick(
        [f"Cool_Auto_{t}" for t in (20, 22, 24, 26)]
        + [f"Heat_Auto_{t}" for t in (20, 22, 24, 26)]
    )
    return {
        "Tadiran_1345.ir": (render(compact, "compact: Off, Cool/Heat auto fan 20-26C"), 9),
        "Tadiran_1345_Cool.ir": (render(mode("Cool"), "Off + all Cool states"), 61),
        "Tadiran_1345_Heat.ir": (render(mode("Heat"), "Off + all Heat states"), 61),
        "Tadiran_1345_full.ir": (render(signals, "all states"), 301),
    }


def ir_blaster_parse(text):
    """Mirror IR Blaster's _parseFlipperIrFile: split on '#', keep raw blocks."""
    buttons = []
    for block in text.split("#"):
        block = block.strip()
        if "type: raw" not in block:
            continue
        name = re.search(r"name:\s*(.+)", block)
        freq = re.search(r"frequency:\s*(\d+)", block)
        data = re.search(r"data:\s*([\d\s]+)", block)
        if name and freq and data:
            buttons.append((name.group(1).strip(), data.group(1).split()))
    return buttons


def check(files):
    for fname, (text, expected) in files.items():
        size = len(text.encode())
        if size > MAX_FILE_BYTES:
            raise SystemExit(f"{fname}: {size} bytes exceeds {MAX_FILE_BYTES}")
        buttons = ir_blaster_parse(text)
        if len(buttons) != expected:
            raise SystemExit(f"{fname}: parsed {len(buttons)} signals, expected {expected}")
        for name, data in buttons:
            if len(data) % 2 or not 0 < len(data) < FLIPPER_MAX_TIMINGS:
                raise SystemExit(f"{fname}: {name} has {len(data)} timings")
        off = [int(x) for x in dict(buttons)["Off"][:4]]
        for got, want in zip(off, OFF_PREFIX):
            if abs(got - want) > want * 0.03:
                raise SystemExit(f"{fname}: Off starts {off}, expected ~{list(OFF_PREFIX)}")


def load_source(source):
    if re.match(r"https?://", source):
        with urllib.request.urlopen(source) as resp:
            return json.load(resp)
    return json.loads(Path(source).read_text())


def main():
    parser = argparse.ArgumentParser(description="Convert SmartIR Broadlink codes to Flipper .ir files")
    parser.add_argument("--source", default=DEFAULT_SOURCE, help="SmartIR JSON path or URL")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="repo root; files go to <out>/ACs/Tadiran (default: script directory)",
    )
    args = parser.parse_args()

    data = load_source(args.source)
    signals = collect_signals(data["commands"])
    files = build_files(signals)
    check(files)
    if build_files(collect_signals(data["commands"])) != files:
        raise SystemExit("output is not deterministic")

    out_dir = args.out / "ACs" / "Tadiran"
    out_dir.mkdir(parents=True, exist_ok=True)
    for fname, (text, count) in files.items():
        (out_dir / fname).write_text(text)
        print(f"{out_dir / fname}: {count} signals, {len(text.encode()) // 1024} KB")
    off = dict(signals)["Off"]
    print("Off starts:", " ".join(map(str, off[:4])))


if __name__ == "__main__":
    sys.exit(main())
